package com.spring.model;
// Generated Dec 31, 2017 2:05:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


     private Integer branchId;
     private String branchName;
     private String branchAddress;
     private String branchPhone;
     private String branchProvince;
     private Set costIncurredAMonths = new HashSet(0);
     private Set dishPriceBranches = new HashSet(0);
     private Set tables = new HashSet(0);
     private Set costIncurredADays = new HashSet(0);
     private Set branchMenus = new HashSet(0);
     private Set orders = new HashSet(0);

    public Branch() {
    }

	
    public Branch(String branchName, String branchAddress, String branchPhone, String branchProvince) {
        this.branchName = branchName;
        this.branchAddress = branchAddress;
        this.branchPhone = branchPhone;
        this.branchProvince = branchProvince;
    }
    public Branch(String branchName, String branchAddress, String branchPhone, String branchProvince, Set costIncurredAMonths, Set dishPriceBranches, Set tables, Set costIncurredADays, Set branchMenus, Set orders) {
       this.branchName = branchName;
       this.branchAddress = branchAddress;
       this.branchPhone = branchPhone;
       this.branchProvince = branchProvince;
       this.costIncurredAMonths = costIncurredAMonths;
       this.dishPriceBranches = dishPriceBranches;
       this.tables = tables;
       this.costIncurredADays = costIncurredADays;
       this.branchMenus = branchMenus;
       this.orders = orders;
    }
   
    public Integer getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public String getBranchAddress() {
        return this.branchAddress;
    }
    
    public void setBranchAddress(String branchAddress) {
        this.branchAddress = branchAddress;
    }
    public String getBranchPhone() {
        return this.branchPhone;
    }
    
    public void setBranchPhone(String branchPhone) {
        this.branchPhone = branchPhone;
    }
    public String getBranchProvince() {
        return this.branchProvince;
    }
    
    public void setBranchProvince(String branchProvince) {
        this.branchProvince = branchProvince;
    }
    public Set getCostIncurredAMonths() {
        return this.costIncurredAMonths;
    }
    
    public void setCostIncurredAMonths(Set costIncurredAMonths) {
        this.costIncurredAMonths = costIncurredAMonths;
    }
    public Set getDishPriceBranches() {
        return this.dishPriceBranches;
    }
    
    public void setDishPriceBranches(Set dishPriceBranches) {
        this.dishPriceBranches = dishPriceBranches;
    }
    public Set getTables() {
        return this.tables;
    }
    
    public void setTables(Set tables) {
        this.tables = tables;
    }
    public Set getCostIncurredADays() {
        return this.costIncurredADays;
    }
    
    public void setCostIncurredADays(Set costIncurredADays) {
        this.costIncurredADays = costIncurredADays;
    }
    public Set getBranchMenus() {
        return this.branchMenus;
    }
    
    public void setBranchMenus(Set branchMenus) {
        this.branchMenus = branchMenus;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


