package com.spring.model;
// Generated Dec 31, 2017 2:05:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DishCategory generated by hbm2java
 */
public class DishCategory  implements java.io.Serializable {


     private Integer dishCategoryId;
     private String dishCategoryName;
     private Set branchMenus = new HashSet(0);
     private Set dishes = new HashSet(0);

    public DishCategory() {
    }

	
    public DishCategory(String dishCategoryName) {
        this.dishCategoryName = dishCategoryName;
    }
    public DishCategory(String dishCategoryName, Set branchMenus, Set dishes) {
       this.dishCategoryName = dishCategoryName;
       this.branchMenus = branchMenus;
       this.dishes = dishes;
    }
   
    public Integer getDishCategoryId() {
        return this.dishCategoryId;
    }
    
    public void setDishCategoryId(Integer dishCategoryId) {
        this.dishCategoryId = dishCategoryId;
    }
    public String getDishCategoryName() {
        return this.dishCategoryName;
    }
    
    public void setDishCategoryName(String dishCategoryName) {
        this.dishCategoryName = dishCategoryName;
    }
    public Set getBranchMenus() {
        return this.branchMenus;
    }
    
    public void setBranchMenus(Set branchMenus) {
        this.branchMenus = branchMenus;
    }
    public Set getDishes() {
        return this.dishes;
    }
    
    public void setDishes(Set dishes) {
        this.dishes = dishes;
    }




}


