package com.spring.model;
// Generated Dec 31, 2017 2:05:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dish generated by hbm2java
 */
public class Dish  implements java.io.Serializable {


     private Integer dishId;
     private DishCategory dishCategory;
     private String dishName;
     private String dishDescription;
     private String dishImage;
     private Set dishPriceBranches = new HashSet(0);
     private Set orderDishes = new HashSet(0);

    public Dish() {
    }

	
    public Dish(DishCategory dishCategory, String dishName, String dishDescription, String dishImage) {
        this.dishCategory = dishCategory;
        this.dishName = dishName;
        this.dishDescription = dishDescription;
        this.dishImage = dishImage;
    }
    public Dish(DishCategory dishCategory, String dishName, String dishDescription, String dishImage, Set dishPriceBranches, Set orderDishes) {
       this.dishCategory = dishCategory;
       this.dishName = dishName;
       this.dishDescription = dishDescription;
       this.dishImage = dishImage;
       this.dishPriceBranches = dishPriceBranches;
       this.orderDishes = orderDishes;
    }
   
    public Integer getDishId() {
        return this.dishId;
    }
    
    public void setDishId(Integer dishId) {
        this.dishId = dishId;
    }
    public DishCategory getDishCategory() {
        return this.dishCategory;
    }
    
    public void setDishCategory(DishCategory dishCategory) {
        this.dishCategory = dishCategory;
    }
    public String getDishName() {
        return this.dishName;
    }
    
    public void setDishName(String dishName) {
        this.dishName = dishName;
    }
    public String getDishDescription() {
        return this.dishDescription;
    }
    
    public void setDishDescription(String dishDescription) {
        this.dishDescription = dishDescription;
    }
    public String getDishImage() {
        return this.dishImage;
    }
    
    public void setDishImage(String dishImage) {
        this.dishImage = dishImage;
    }
    public Set getDishPriceBranches() {
        return this.dishPriceBranches;
    }
    
    public void setDishPriceBranches(Set dishPriceBranches) {
        this.dishPriceBranches = dishPriceBranches;
    }
    public Set getOrderDishes() {
        return this.orderDishes;
    }
    
    public void setOrderDishes(Set orderDishes) {
        this.orderDishes = orderDishes;
    }




}


