package com.spring.model;
// Generated Dec 31, 2017 2:05:26 PM by Hibernate Tools 4.3.1



/**
 * DishPriceBranchId generated by hbm2java
 */
public class DishPriceBranchId  implements java.io.Serializable {


     private int dishId;
     private int branchId;

    public DishPriceBranchId() {
    }

    public DishPriceBranchId(int dishId, int branchId) {
       this.dishId = dishId;
       this.branchId = branchId;
    }
   
    public int getDishId() {
        return this.dishId;
    }
    
    public void setDishId(int dishId) {
        this.dishId = dishId;
    }
    public int getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DishPriceBranchId) ) return false;
		 DishPriceBranchId castOther = ( DishPriceBranchId ) other; 
         
		 return (this.getDishId()==castOther.getDishId())
 && (this.getBranchId()==castOther.getBranchId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDishId();
         result = 37 * result + this.getBranchId();
         return result;
   }   


}


