package com.spring.model;
// Generated Dec 31, 2017 2:05:26 PM by Hibernate Tools 4.3.1



/**
 * DishPriceBranch generated by hbm2java
 */
public class DishPriceBranch  implements java.io.Serializable {


     private DishPriceBranchId id;
     private Branch branch;
     private Dish dish;
     private int price;
     private int amount;

    public DishPriceBranch() {
    }

    public DishPriceBranch(DishPriceBranchId id, Branch branch, Dish dish, int price, int amount) {
       this.id = id;
       this.branch = branch;
       this.dish = dish;
       this.price = price;
       this.amount = amount;
    }
   
    public DishPriceBranchId getId() {
        return this.id;
    }
    
    public void setId(DishPriceBranchId id) {
        this.id = id;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public Dish getDish() {
        return this.dish;
    }
    
    public void setDish(Dish dish) {
        this.dish = dish;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }




}


