package com.spring.model;
// Generated Dec 31, 2017 2:05:26 PM by Hibernate Tools 4.3.1



/**
 * Info generated by hbm2java
 */
public class Info  implements java.io.Serializable {


     private Integer infoId;
     private String hotline;
     private String introduction;

    public Info() {
    }

    public Info(String hotline, String introduction) {
       this.hotline = hotline;
       this.introduction = introduction;
    }
   
    public Integer getInfoId() {
        return this.infoId;
    }
    
    public void setInfoId(Integer infoId) {
        this.infoId = infoId;
    }
    public String getHotline() {
        return this.hotline;
    }
    
    public void setHotline(String hotline) {
        this.hotline = hotline;
    }
    public String getIntroduction() {
        return this.introduction;
    }
    
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }




}


