package com.spring.model;
// Generated Dec 31, 2017 2:05:26 PM by Hibernate Tools 4.3.1



/**
 * OrderDishId generated by hbm2java
 */
public class OrderDishId  implements java.io.Serializable {


     private int orderId;
     private int dishId;

    public OrderDishId() {
    }

    public OrderDishId(int orderId, int dishId) {
       this.orderId = orderId;
       this.dishId = dishId;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getDishId() {
        return this.dishId;
    }
    
    public void setDishId(int dishId) {
        this.dishId = dishId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderDishId) ) return false;
		 OrderDishId castOther = ( OrderDishId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getDishId()==castOther.getDishId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getDishId();
         return result;
   }   


}


