package com.spring.model;
// Generated Dec 31, 2017 2:05:26 PM by Hibernate Tools 4.3.1



/**
 * OrderDish generated by hbm2java
 */
public class OrderDish  implements java.io.Serializable {


     private OrderDishId id;
     private Dish dish;
     private Order order;
     private int amount;

    public OrderDish() {
    }

    public OrderDish(OrderDishId id, Dish dish, Order order, int amount) {
       this.id = id;
       this.dish = dish;
       this.order = order;
       this.amount = amount;
    }
   
    public OrderDishId getId() {
        return this.id;
    }
    
    public void setId(OrderDishId id) {
        this.id = id;
    }
    public Dish getDish() {
        return this.dish;
    }
    
    public void setDish(Dish dish) {
        this.dish = dish;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }




}


