package com.spring.model;
// Generated Dec 31, 2017 2:05:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer orderId;
     private Branch branch;
     private Client client;
     private int orderStatus;
     private Date dateApprove;
     private Date dateDelivery;
     private int orderType;
     private Set orderDishes = new HashSet(0);

    public Order() {
    }

	
    public Order(Branch branch, Client client, int orderStatus, int orderType) {
        this.branch = branch;
        this.client = client;
        this.orderStatus = orderStatus;
        this.orderType = orderType;
    }
    public Order(Branch branch, Client client, int orderStatus, Date dateApprove, Date dateDelivery, int orderType, Set orderDishes) {
       this.branch = branch;
       this.client = client;
       this.orderStatus = orderStatus;
       this.dateApprove = dateApprove;
       this.dateDelivery = dateDelivery;
       this.orderType = orderType;
       this.orderDishes = orderDishes;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public int getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(int orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Date getDateApprove() {
        return this.dateApprove;
    }
    
    public void setDateApprove(Date dateApprove) {
        this.dateApprove = dateApprove;
    }
    public Date getDateDelivery() {
        return this.dateDelivery;
    }
    
    public void setDateDelivery(Date dateDelivery) {
        this.dateDelivery = dateDelivery;
    }
    public int getOrderType() {
        return this.orderType;
    }
    
    public void setOrderType(int orderType) {
        this.orderType = orderType;
    }
    public Set getOrderDishes() {
        return this.orderDishes;
    }
    
    public void setOrderDishes(Set orderDishes) {
        this.orderDishes = orderDishes;
    }




}


