package com.spring.model;
// Generated Dec 31, 2017 2:05:26 PM by Hibernate Tools 4.3.1



/**
 * Table generated by hbm2java
 */
public class Table  implements java.io.Serializable {


     private Integer tableId;
     private Branch branch;
     private String tableName;
     private int tableStatus;

    public Table() {
    }

    public Table(Branch branch, String tableName, int tableStatus) {
       this.branch = branch;
       this.tableName = tableName;
       this.tableStatus = tableStatus;
    }
   
    public Integer getTableId() {
        return this.tableId;
    }
    
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public int getTableStatus() {
        return this.tableStatus;
    }
    
    public void setTableStatus(int tableStatus) {
        this.tableStatus = tableStatus;
    }




}


